name: Run Tests

# Especificamos que el workflow se ejecuta en cada push o pull request a la rama master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # Puedes cambiar la versión de Python según lo que uses

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Asegúrate de tener tus dependencias aquí

    - name: Run unit tests
      run: |
        pytest test/test_file.py  # Ejecuta tus tests en el archivo test_file.py
